### ISSUE TITLE
Training poorly on custom data.

### ISSUE THREAD

**Issue by dennisushi** [subhc/unsup-parts#7]
Hi, I am trying to train the network on a custom dataset of shoes. After training overnight the parts still don't looks great. Could you please give some pointers as to what could be improved? Would the fact that some shoe images are cropped at the corners affect the training?  I see that the semantic loss doesn't really go down and am wondering why that would be. 
 
![image](https://user-images.githubusercontent.com/30011340/160087411-e7667391-05e4-4b41-894c-e8966cb78618.png)

![image](https://user-images.githubusercontent.com/30011340/160087280-5a8c4063-c27b-4401-b5ef-171539ad51f3.png)

**Comment by subhc** [comment]
Thank you for your interest in our work! 
It may be because the resnet features are not discriminative enough for shoes. You can try changing the semantic loss features to DINO ViT, In a related paper the authors seem to perform good segmentations on shoes https://dino-vit-features.github.io/ with it. I would also experiment with a stonger equivariance loss eg. maybe with random_mirror enabled and with higher loss coefficient.
